<?php
/**
 * Select for sorter
 */
?>

<script type="text/x-magento-init">
    {
    "*": {
        "elogicSelect": {
            "selector":"#sorter",
            "selectOptions":{}
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>
<?php
/**
 * Sidebar Slider
 */
?>

<script type="text/x-magento-init">
    {
    ".sidebar-main-baner": {
        "elogicSlider": {
            "selector":".sidebar-baner-list",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
    }
</script>
<?php
    /**
    *  Select options
    */
    ?>

    <script type="text/x-magento-init">
    {
    ".field.limiter": {
        "elogicSelect": {
            "selector":".control #limiter"
        }
    }
    }
</script>
