<?php
/**
 * @var $block \Mirasvit\Giftr\Block\Item\Add
 * added html for modal and init modal
 *
 */
?>


<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Select Gift Registry',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
        }}">
    <div class="content">
        <div class="giftr-list"  style="display: block"
             data-bind="scope: 'giftr-addto__form'">

            <div class="registry-list" data-bind="visible: hasRegistries">

                <div class="initial-select">
                    Select Category
                </div>

                <div class="registries registries-container" data-bind="foreach: registries">
                    <label for="registry_>" class="label option" data-bind="attr: { for: 'registry_' + value }">
                        <input type="checkbox" id="registry_" name="registries[]" value=""
                               data-bind="checked: $parent.selected, value: value, attr: { id: 'registry_' + value }" />
                        <span data-bind="text: label"></span>
                    </label>
                </div>

                <a id="confirm-add-to-registry" href="#" data-bind="click: addProduct"><?= __('Add to Gift Registry') ?></a>
            </div>

            <div data-bind="visible: isMessageVisible()">
                <span data-bind="html: getMessage()"></span>
            </div>
        </div>
    </div>
</div>


<script type="text/x-magento-init">
{
    "*": {
        "modalSelect": {
            "registries_container": ".registries-container",
            "registry_list": ".option",
            "initialSelect": ".initial-select"
        }
    }
}
</script>
