// INIT SLIDERS
<script type="text/x-magento-init">
    {
    "*": {
        "elogicSlider": {
            "selector":".general-baner-wrapper",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "infinite": false,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
    }
</script>


<script type="text/x-magento-init">
{
    ".container.our-product-container": {
        "elogicSlider": {
            "selector":" .our-product-container  .product-items",
            "sliderOptions":{
                "slidesToShow": 4,
                "slidesToScroll": 4,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": 3,
                            "slidesToScroll": 3
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 2
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
}
</script>

<script type="text/x-magento-init">
    {
    "*": {
        "elogicSlider": {
            "selector":".grid-container .product-items",
            "sliderOptions":{
                "dots": false,
                "arrows": true,
                "rows": 3,
                "slidesToShow": 1,
		        "slidesToScroll": 1
            }
        }
    }
    }
</script>

<script type="text/x-magento-init">
    {
    "*": {
        "elogicSlider": {
            "selector":".blog-list",
            "sliderOptions":{
                "slidesToShow": 3,
                "slidesToScroll": 3,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 2
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
    }
</script>

<script type="text/x-magento-init">
    {
    "*": {
        "elogicSlider": {
            "selector":".brand-list",
            "sliderOptions":{
                "slidesToShow": 5,
                "slidesToScroll": 5,
                "centerMode": true,
                "dots": true,
                "autoplay": true,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": 4
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 3
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }
    }
    }
</script>
