<!-- INIT SLIDERS-->
<script type="text/x-magento-init">
{
    ".container.gallery-page": {
        "elogicSlider":{
            "selector":".gallery-list",
            "sliderOptions":{
                "slidesToShow": 3,
                "centerMode": true,
                "arrows": true,
                "dots":true,
                "responsive": [
                    {
                        "breakpoint": 992,
                        "settings": {
                            "slidesToShow": 2
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }

    }
    }



</script>

